import { verifyAuth } from "@/lib/auth";

import HeaderSection from "@/components/header/headerSection";

export const metadata = {
  title: "ShopHere App",
  description: "Generated by Gds..",
};

export default async function HomeLayout({ children }) {
  const result = await verifyAuth();

  return (
    <html lang="en">
      <body>
        <HeaderSection isLogin={result} />
        {children}
      </body>
    </html>
  );
}
