"use client";

import "./globals.css";
import { usePathname } from "next/navigation";
import HeaderSection from "@/components/header/headerSection";

// export const metadata = {
//   title: "ShopHere App",
//   description: "Generated by Gds..",
// };

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const noHeaderRoutes = ["/authentication"];
  return (
    <html lang="en">
      <body>
        {!noHeaderRoutes.includes(pathname) && <HeaderSection />}
        {children}
      </body>
    </html>
  );
}
